import React from 'react'

export const Category = () => {
  return (
    <div>
      Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minus accusantium iste, perspiciatis omnis pariatur quaerat cumque alias odit eos deserunt. Recusandae consequatur illum, vero, aut iusto excepturi sint quos enim quaerat fugiat facilis expedita doloremque doloribus corrupti, mollitia quia adipisci qui quasi asperiores. Ratione sunt minima placeat quo magnam porro esse officia minus dolorem. Error nobis ipsa rerum similique dolore natus optio est nemo, quidem nostrum sunt libero quo iure cumque aliquam alias ea accusamus aliquid tempore molestiae inventore non. Ab ipsam iusto eaque! Accusamus illo ex nihil praesentium, quo architecto numquam quidem ipsam dolor, nulla est molestias voluptate ullam eius earum velit id iste animi voluptatum ratione, aperiam saepe? Pariatur eaque consequatur officiis commodi rem sequi provident exercitationem impedit! Quibusdam, impedit iusto. Autem, sit? Ut, illo veritatis! Odit molestias adipisci neque repellat suscipit rerum similique minima ex. Est ipsam quia quas autem. Vel delectus dolor molestias debitis aperiam sed dignissimos eius dolore! Accusantium ipsum eveniet nihil, quidem veritatis perferendis odio beatae ex aliquam facere nobis illo quaerat, provident nulla cupiditate reiciendis impedit ipsa tempora, reprehenderit asperiores sit quo! Eveniet veritatis porro dignissimos pariatur. Eveniet beatae debitis repudiandae similique! At eum debitis dolorum exercitationem consectetur aperiam ipsum nisi! Cupiditate optio error sequi, obcaecati corporis voluptatum mollitia architecto debitis labore eum totam illum odit eveniet ex earum non ab natus modi, vero aliquid consequatur ipsa. Animi iusto corrupti repellat ipsam fuga, eius perspiciatis deserunt deleniti rem voluptatibus repudiandae saepe ex accusantium similique laudantium distinctio minima, inventore incidunt a, in aliquam officia. Totam sed eius est voluptates dicta enim aspernatur, facere ex itaque voluptatibus ipsam quae ducimus eaque unde neque eveniet natus repudiandae omnis saepe aliquam dignissimos? Corrupti maiores molestiae rem. Sequi nam, culpa quia deserunt magnam consequatur. Dignissimos nisi quisquam nam ipsa aut totam consequatur. Sit quisquam ad dolorem quibusdam nemo.
    </div>
  )
}
